version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: prova
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    build: .
    command: node ace serve --watch
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app
